### ISSUE TITLE
hwameistor启用drbd失败

### ISSUE THREAD

**Issue by bill-ding007** [hwameistor/drbd-adapter#58]
启用hwameistor的drbd失败：

查看hwameistor的cr:`kubectl get clusters.hwameistor.io hwameistor-cluster -oyaml`
```
apiVersion: hwameistor.io/v1alpha1
kind: Cluster
metadata:
  ...
  drbd:
    chartVersion: v0.3.6
    checkHostName: "yes"
    deployOnMaster: "yes"
    disable: false
...
```
查看pvc： `kubectl describe pvc xxx-pvc`:
```
failed to provision volume with StorageClass "hwameistor-storage-lvm-hdd-ha": rpc error: code = Unavailable desc = LocalVolume pvc-59be2f2b-bd30-40f5-931b-a019445d8210 is NotReady(deadline exceeded)
```

查看sc： `kubectl get sc hwameistor-storage-lvm-hdd-ha -oyaml`:
```
llowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  name: hwameistor-storage-lvm-hdd-ha
parameters:
  convertible: "false"
  csi.storage.k8s.io/fstype: xfs
  poolClass: HDD
  poolType: REGULAR
  replicaNumber: "2"
  striped: "true"
  volumeKind: LVM
provisioner: lvm.hwameistor.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
